/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */
module Google.Apis.Gmail.v1.Data.BatchDeleteMessagesRequest;

import vibe.data.json: optional;
import std.typecons: Nullable;
import std.datetime : SysTime;
import std.conv: to;

import Google.Apis.Gmail.v1.GmailMyNullable;

/**
 * Model definition for BatchDeleteMessagesRequest.
 *
 * This is the D data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Gmail API. For a detailed explanation see:
 *
 *
 * @author Robert Aron.
 */
public struct BatchDeleteMessagesRequest {

  /**
   * The IDs of the messages to delete.
   * The value may be {@code null}.
   */
  @optional public string[] _ids;

  /**
   * The IDs of the messages to delete.
   * @return value or {@code null} for none
   */
  public string[] getIds() {
    return _ids;
  }
  /**
   * The IDs of the messages to delete.
   * @param ids ids or {@code null} for none
   */
  public BatchDeleteMessagesRequest setIds(string[] _ids) {
    this._ids = _ids;
    return this;
  }

}