/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */
module Google.Apis.Gmail.v1.Data.Filter;

import vibe.data.json: optional;
import std.typecons: Nullable;
import std.datetime : SysTime;
import std.conv: to;

import Google.Apis.Gmail.v1.GmailMyNullable;

import Google.Apis.Gmail.v1.Data.FilterAction;
import Google.Apis.Gmail.v1.Data.FilterCriteria;

/**
 * Resource definition for Gmail filters. Filters apply to specific messages instead of an entire
 * email thread.
 *
 * This is the D data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Gmail API. For a detailed explanation see:
 *
 *
 * @author Robert Aron.
 */
public struct Filter {

  /**
   * Action that the filter performs.
   * The value may be {@code null}.
   */
  @optional public FilterAction _action;

  /**
   * Matching criteria for the filter.
   * The value may be {@code null}.
   */
  @optional public FilterCriteria _criteria;

  /**
   * The server assigned ID of the filter.
   * The value may be {@code null}.
   */
  @optional public string _id;

  /**
   * Action that the filter performs.
   * @return value or {@code null} for none
   */
  public FilterAction getAction() {
    return _action;
  }
  /**
   * Action that the filter performs.
   * @param action action or {@code null} for none
   */
  public Filter setAction(FilterAction _action) {
    this._action = _action;
    return this;
  }

  /**
   * Matching criteria for the filter.
   * @return value or {@code null} for none
   */
  public FilterCriteria getCriteria() {
    return _criteria;
  }
  /**
   * Matching criteria for the filter.
   * @param criteria criteria or {@code null} for none
   */
  public Filter setCriteria(FilterCriteria _criteria) {
    this._criteria = _criteria;
    return this;
  }

  /**
   * The server assigned ID of the filter.
   * @return value or {@code null} for none
   */
  public string getId() {
    return _id;
  }
  /**
   * The server assigned ID of the filter.
   * @param id id or {@code null} for none
   */
  public Filter setId(string _id) {
    this._id = _id;
    return this;
  }

}