/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */
module Google.Apis.Gmail.v1.Data.ForwardingAddress;

import vibe.data.json: optional;
import std.typecons: Nullable;
import std.datetime : SysTime;
import std.conv: to;

import Google.Apis.Gmail.v1.GmailMyNullable;

/**
 * Settings for a forwarding address.
 *
 * This is the D data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Gmail API. For a detailed explanation see:
 *
 *
 * @author Robert Aron.
 */
public struct ForwardingAddress {

  /**
   * An email address to which messages can be forwarded.
   * The value may be {@code null}.
   */
  @optional public string _forwardingEmail;

  /**
   * Indicates whether this address has been verified and is usable for forwarding. Read-only.
   * The value may be {@code null}.
   */
  @optional public string _verificationStatus;

  /**
   * An email address to which messages can be forwarded.
   * @return value or {@code null} for none
   */
  public string getForwardingEmail() {
    return _forwardingEmail;
  }
  /**
   * An email address to which messages can be forwarded.
   * @param forwardingEmail forwardingEmail or {@code null} for none
   */
  public ForwardingAddress setForwardingEmail(string _forwardingEmail) {
    this._forwardingEmail = _forwardingEmail;
    return this;
  }

  /**
   * Indicates whether this address has been verified and is usable for forwarding. Read-only.
   * @return value or {@code null} for none
   */
  public string getVerificationStatus() {
    return _verificationStatus;
  }
  /**
   * Indicates whether this address has been verified and is usable for forwarding. Read-only.
   * @param verificationStatus verificationStatus or {@code null} for none
   */
  public ForwardingAddress setVerificationStatus(string _verificationStatus) {
    this._verificationStatus = _verificationStatus;
    return this;
  }

}