/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */
module Google.Apis.Gmail.v1.Data.History;

import vibe.data.json: optional;
import std.typecons: Nullable;
import std.datetime : SysTime;
import std.conv: to;

import Google.Apis.Gmail.v1.GmailMyNullable;

import Google.Apis.Gmail.v1.Data.HistoryLabelAdded;
import Google.Apis.Gmail.v1.Data.HistoryLabelRemoved;
import Google.Apis.Gmail.v1.Data.Message;
import Google.Apis.Gmail.v1.Data.HistoryMessageAdded;
import Google.Apis.Gmail.v1.Data.HistoryMessageDeleted;

/**
 * A record of a change to the user's mailbox. Each history change may affect multiple messages in
 * multiple ways.
 *
 * This is the D data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Gmail API. For a detailed explanation see:
 *
 *
 * @author Robert Aron.
 */
public struct History {

  /**
   * The mailbox sequence ID.
   * The value may be {@code null}.
   */
  @optional public MyNullable!ulong _id;

  /**
   * Labels added to messages in this history record.
   * The value may be {@code null}.
   */
  @optional public HistoryLabelAdded[] _labelsAdded;

  /**
   * Labels removed from messages in this history record.
   * The value may be {@code null}.
   */
  @optional public HistoryLabelRemoved[] _labelsRemoved;

  /**
   * List of messages changed in this history record. The fields for specific change types, such as
   * `messagesAdded` may duplicate messages in this field. We recommend using the specific change-
   * type fields instead of this.
   * The value may be {@code null}.
   */
  @optional public Message[] _messages;

  /**
   * Messages added to the mailbox in this history record.
   * The value may be {@code null}.
   */
  @optional public HistoryMessageAdded[] _messagesAdded;

  /**
   * Messages deleted (not Trashed) from the mailbox in this history record.
   * The value may be {@code null}.
   */
  @optional public HistoryMessageDeleted[] _messagesDeleted;

  /**
   * The mailbox sequence ID.
   * @return value or {@code null} for none
   */
  public MyNullable!ulong getId() {
    return _id;
  }
  /**
   * The mailbox sequence ID.
   * @param id id or {@code null} for none
   */
  public History setId(MyNullable!ulong _id) {
    this._id = _id;
    return this;
  }

  /**
   * Labels added to messages in this history record.
   * @return value or {@code null} for none
   */
  public HistoryLabelAdded[] getLabelsAdded() {
    return _labelsAdded;
  }
  /**
   * Labels added to messages in this history record.
   * @param labelsAdded labelsAdded or {@code null} for none
   */
  public History setLabelsAdded(HistoryLabelAdded[] _labelsAdded) {
    this._labelsAdded = _labelsAdded;
    return this;
  }

  /**
   * Labels removed from messages in this history record.
   * @return value or {@code null} for none
   */
  public HistoryLabelRemoved[] getLabelsRemoved() {
    return _labelsRemoved;
  }
  /**
   * Labels removed from messages in this history record.
   * @param labelsRemoved labelsRemoved or {@code null} for none
   */
  public History setLabelsRemoved(HistoryLabelRemoved[] _labelsRemoved) {
    this._labelsRemoved = _labelsRemoved;
    return this;
  }

  /**
   * List of messages changed in this history record. The fields for specific change types, such as
   * `messagesAdded` may duplicate messages in this field. We recommend using the specific change-
   * type fields instead of this.
   * @return value or {@code null} for none
   */
  public Message[] getMessages() {
    return _messages;
  }
  /**
   * List of messages changed in this history record. The fields for specific change types, such as
   * `messagesAdded` may duplicate messages in this field. We recommend using the specific change-
   * type fields instead of this.
   * @param messages messages or {@code null} for none
   */
  public History setMessages(Message[] _messages) {
    this._messages = _messages;
    return this;
  }

  /**
   * Messages added to the mailbox in this history record.
   * @return value or {@code null} for none
   */
  public HistoryMessageAdded[] getMessagesAdded() {
    return _messagesAdded;
  }
  /**
   * Messages added to the mailbox in this history record.
   * @param messagesAdded messagesAdded or {@code null} for none
   */
  public History setMessagesAdded(HistoryMessageAdded[] _messagesAdded) {
    this._messagesAdded = _messagesAdded;
    return this;
  }

  /**
   * Messages deleted (not Trashed) from the mailbox in this history record.
   * @return value or {@code null} for none
   */
  public HistoryMessageDeleted[] getMessagesDeleted() {
    return _messagesDeleted;
  }
  /**
   * Messages deleted (not Trashed) from the mailbox in this history record.
   * @param messagesDeleted messagesDeleted or {@code null} for none
   */
  public History setMessagesDeleted(HistoryMessageDeleted[] _messagesDeleted) {
    this._messagesDeleted = _messagesDeleted;
    return this;
  }

}