/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */
module Google.Apis.Gmail.v1.Data.ListHistoryResponse;

import vibe.data.json: optional;
import std.typecons: Nullable;
import std.datetime : SysTime;
import std.conv: to;

import Google.Apis.Gmail.v1.GmailMyNullable;

import Google.Apis.Gmail.v1.Data.History;

/**
 * Model definition for ListHistoryResponse.
 *
 * This is the D data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Gmail API. For a detailed explanation see:
 *
 *
 * @author Robert Aron.
 */
public struct ListHistoryResponse {

  /**
   * List of history records. Any `messages` contained in the response will typically only have `id`
   * and `threadId` fields populated.
   * The value may be {@code null}.
   */
  @optional public History[] _history;

  /**
   * The ID of the mailbox's current history record.
   * The value may be {@code null}.
   */
  @optional public MyNullable!ulong _historyId;

  /**
   * Page token to retrieve the next page of results in the list.
   * The value may be {@code null}.
   */
  @optional public string _nextPageToken;

  /**
   * List of history records. Any `messages` contained in the response will typically only have `id`
   * and `threadId` fields populated.
   * @return value or {@code null} for none
   */
  public History[] getHistory() {
    return _history;
  }
  /**
   * List of history records. Any `messages` contained in the response will typically only have `id`
   * and `threadId` fields populated.
   * @param history history or {@code null} for none
   */
  public ListHistoryResponse setHistory(History[] _history) {
    this._history = _history;
    return this;
  }

  /**
   * The ID of the mailbox's current history record.
   * @return value or {@code null} for none
   */
  public MyNullable!ulong getHistoryId() {
    return _historyId;
  }
  /**
   * The ID of the mailbox's current history record.
   * @param historyId historyId or {@code null} for none
   */
  public ListHistoryResponse setHistoryId(MyNullable!ulong _historyId) {
    this._historyId = _historyId;
    return this;
  }

  /**
   * Page token to retrieve the next page of results in the list.
   * @return value or {@code null} for none
   */
  public string getNextPageToken() {
    return _nextPageToken;
  }
  /**
   * Page token to retrieve the next page of results in the list.
   * @param nextPageToken nextPageToken or {@code null} for none
   */
  public ListHistoryResponse setNextPageToken(string _nextPageToken) {
    this._nextPageToken = _nextPageToken;
    return this;
  }

}