/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */
module Google.Apis.Gmail.v1.Data.MessagePartHeader;

import vibe.data.json: optional;
import std.typecons: Nullable;
import std.datetime : SysTime;
import std.conv: to;

import Google.Apis.Gmail.v1.GmailMyNullable;

/**
 * Model definition for MessagePartHeader.
 *
 * This is the D data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Gmail API. For a detailed explanation see:
 *
 *
 * @author Robert Aron.
 */
public struct MessagePartHeader {

  /**
   * The name of the header before the `:` separator. For example, `To`.
   * The value may be {@code null}.
   */
  @optional public string _name;

  /**
   * The value of the header after the `:` separator. For example, `someuser@example.com`.
   * The value may be {@code null}.
   */
  @optional public string _value;

  /**
   * The name of the header before the `:` separator. For example, `To`.
   * @return value or {@code null} for none
   */
  public string getName() {
    return _name;
  }
  /**
   * The name of the header before the `:` separator. For example, `To`.
   * @param name name or {@code null} for none
   */
  public MessagePartHeader setName(string _name) {
    this._name = _name;
    return this;
  }

  /**
   * The value of the header after the `:` separator. For example, `someuser@example.com`.
   * @return value or {@code null} for none
   */
  public string getValue() {
    return _value;
  }
  /**
   * The value of the header after the `:` separator. For example, `someuser@example.com`.
   * @param value value or {@code null} for none
   */
  public MessagePartHeader setValue(string _value) {
    this._value = _value;
    return this;
  }

}