/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */
module Google.Apis.Gmail.v1.Data.Profile;

import vibe.data.json: optional;
import std.typecons: Nullable;
import std.datetime : SysTime;
import std.conv: to;

import Google.Apis.Gmail.v1.GmailMyNullable;

/**
 * Profile for a Gmail user.
 *
 * This is the D data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Gmail API. For a detailed explanation see:
 *
 *
 * @author Robert Aron.
 */
public struct Profile {

  /**
   * The user's email address.
   * The value may be {@code null}.
   */
  @optional public string _emailAddress;

  /**
   * The ID of the mailbox's current history record.
   * The value may be {@code null}.
   */
  @optional public MyNullable!ulong _historyId;

  /**
   * The total number of messages in the mailbox.
   * The value may be {@code null}.
   */
  @optional public Nullable!int _messagesTotal;

  /**
   * The total number of threads in the mailbox.
   * The value may be {@code null}.
   */
  @optional public Nullable!int _threadsTotal;

  /**
   * The user's email address.
   * @return value or {@code null} for none
   */
  public string getEmailAddress() {
    return _emailAddress;
  }
  /**
   * The user's email address.
   * @param emailAddress emailAddress or {@code null} for none
   */
  public Profile setEmailAddress(string _emailAddress) {
    this._emailAddress = _emailAddress;
    return this;
  }

  /**
   * The ID of the mailbox's current history record.
   * @return value or {@code null} for none
   */
  public MyNullable!ulong getHistoryId() {
    return _historyId;
  }
  /**
   * The ID of the mailbox's current history record.
   * @param historyId historyId or {@code null} for none
   */
  public Profile setHistoryId(MyNullable!ulong _historyId) {
    this._historyId = _historyId;
    return this;
  }

  /**
   * The total number of messages in the mailbox.
   * @return value or {@code null} for none
   */
  public Nullable!int getMessagesTotal() {
    return _messagesTotal;
  }
  /**
   * The total number of messages in the mailbox.
   * @param messagesTotal messagesTotal or {@code null} for none
   */
  public Profile setMessagesTotal(Nullable!int _messagesTotal) {
    this._messagesTotal = _messagesTotal;
    return this;
  }

  /**
   * The total number of threads in the mailbox.
   * @return value or {@code null} for none
   */
  public Nullable!int getThreadsTotal() {
    return _threadsTotal;
  }
  /**
   * The total number of threads in the mailbox.
   * @param threadsTotal threadsTotal or {@code null} for none
   */
  public Profile setThreadsTotal(Nullable!int _threadsTotal) {
    this._threadsTotal = _threadsTotal;
    return this;
  }

}