/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */
module Google.Apis.Gmail.v1.Data.Thread;

import vibe.data.json: optional;
import std.typecons: Nullable;
import std.datetime : SysTime;
import std.conv: to;

import Google.Apis.Gmail.v1.GmailMyNullable;

import Google.Apis.Gmail.v1.Data.Message;

/**
 * A collection of messages representing a conversation.
 *
 * This is the D data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Gmail API. For a detailed explanation see:
 *
 *
 * @author Robert Aron.
 */
public struct Thread {

  /**
   * The ID of the last history record that modified this thread.
   * The value may be {@code null}.
   */
  @optional public MyNullable!ulong _historyId;

  /**
   * The unique ID of the thread.
   * The value may be {@code null}.
   */
  @optional public string _id;

  /**
   * The list of messages in the thread.
   * The value may be {@code null}.
   */
  @optional public Message[] _messages;

  /**
   * A short part of the message text.
   * The value may be {@code null}.
   */
  @optional public string _snippet;

  /**
   * The ID of the last history record that modified this thread.
   * @return value or {@code null} for none
   */
  public MyNullable!ulong getHistoryId() {
    return _historyId;
  }
  /**
   * The ID of the last history record that modified this thread.
   * @param historyId historyId or {@code null} for none
   */
  public Thread setHistoryId(MyNullable!ulong _historyId) {
    this._historyId = _historyId;
    return this;
  }

  /**
   * The unique ID of the thread.
   * @return value or {@code null} for none
   */
  public string getId() {
    return _id;
  }
  /**
   * The unique ID of the thread.
   * @param id id or {@code null} for none
   */
  public Thread setId(string _id) {
    this._id = _id;
    return this;
  }

  /**
   * The list of messages in the thread.
   * @return value or {@code null} for none
   */
  public Message[] getMessages() {
    return _messages;
  }
  /**
   * The list of messages in the thread.
   * @param messages messages or {@code null} for none
   */
  public Thread setMessages(Message[] _messages) {
    this._messages = _messages;
    return this;
  }

  /**
   * A short part of the message text.
   * @return value or {@code null} for none
   */
  public string getSnippet() {
    return _snippet;
  }
  /**
   * A short part of the message text.
   * @param snippet snippet or {@code null} for none
   */
  public Thread setSnippet(string _snippet) {
    this._snippet = _snippet;
    return this;
  }

}