/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */
module Google.Apis.Gmail.v1.Data.VacationSettings;

import vibe.data.json: optional;
import std.typecons: Nullable;
import std.datetime : SysTime;
import std.conv: to;

import Google.Apis.Gmail.v1.GmailMyNullable;

/**
 * Vacation auto-reply settings for an account. These settings correspond to the "Vacation
 * responder" feature in the web interface.
 *
 * This is the D data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Gmail API. For a detailed explanation see:
 *
 *
 * @author Robert Aron.
 */
public struct VacationSettings {

  /**
   * Flag that controls whether Gmail automatically replies to messages.
   * The value may be {@code null}.
   */
  @optional public Nullable!bool _enableAutoReply;

  /**
   * An optional end time for sending auto-replies (epoch ms). When this is specified, Gmail will
   * automatically reply only to messages that it receives before the end time. If both `startTime`
   * and `endTime` are specified, `startTime` must precede `endTime`.
   * The value may be {@code null}.
   */
  @optional public MyNullable!long _endTime;

  /**
   * Response body in HTML format. Gmail will sanitize the HTML before storing it. If both
   * `response_body_plain_text` and `response_body_html` are specified, `response_body_html` will be
   * used.
   * The value may be {@code null}.
   */
  @optional public string _responseBodyHtml;

  /**
   * Response body in plain text format. If both `response_body_plain_text` and `response_body_html`
   * are specified, `response_body_html` will be used.
   * The value may be {@code null}.
   */
  @optional public string _responseBodyPlainText;

  /**
   * Optional text to prepend to the subject line in vacation responses. In order to enable auto-
   * replies, either the response subject or the response body must be nonempty.
   * The value may be {@code null}.
   */
  @optional public string _responseSubject;

  /**
   * Flag that determines whether responses are sent to recipients who are not in the user's list of
   * contacts.
   * The value may be {@code null}.
   */
  @optional public Nullable!bool _restrictToContacts;

  /**
   * Flag that determines whether responses are sent to recipients who are outside of the user's
   * domain. This feature is only available for G Suite users.
   * The value may be {@code null}.
   */
  @optional public Nullable!bool _restrictToDomain;

  /**
   * An optional start time for sending auto-replies (epoch ms). When this is specified, Gmail will
   * automatically reply only to messages that it receives after the start time. If both `startTime`
   * and `endTime` are specified, `startTime` must precede `endTime`.
   * The value may be {@code null}.
   */
  @optional public MyNullable!long _startTime;

  /**
   * Flag that controls whether Gmail automatically replies to messages.
   * @return value or {@code null} for none
   */
  public Nullable!bool getEnableAutoReply() {
    return _enableAutoReply;
  }
  /**
   * Flag that controls whether Gmail automatically replies to messages.
   * @param enableAutoReply enableAutoReply or {@code null} for none
   */
  public VacationSettings setEnableAutoReply(Nullable!bool _enableAutoReply) {
    this._enableAutoReply = _enableAutoReply;
    return this;
  }

  /**
   * An optional end time for sending auto-replies (epoch ms). When this is specified, Gmail will
   * automatically reply only to messages that it receives before the end time. If both `startTime`
   * and `endTime` are specified, `startTime` must precede `endTime`.
   * @return value or {@code null} for none
   */
  public MyNullable!long getEndTime() {
    return _endTime;
  }
  /**
   * An optional end time for sending auto-replies (epoch ms). When this is specified, Gmail will
   * automatically reply only to messages that it receives before the end time. If both `startTime`
   * and `endTime` are specified, `startTime` must precede `endTime`.
   * @param endTime endTime or {@code null} for none
   */
  public VacationSettings setEndTime(MyNullable!long _endTime) {
    this._endTime = _endTime;
    return this;
  }

  /**
   * Response body in HTML format. Gmail will sanitize the HTML before storing it. If both
   * `response_body_plain_text` and `response_body_html` are specified, `response_body_html` will be
   * used.
   * @return value or {@code null} for none
   */
  public string getResponseBodyHtml() {
    return _responseBodyHtml;
  }
  /**
   * Response body in HTML format. Gmail will sanitize the HTML before storing it. If both
   * `response_body_plain_text` and `response_body_html` are specified, `response_body_html` will be
   * used.
   * @param responseBodyHtml responseBodyHtml or {@code null} for none
   */
  public VacationSettings setResponseBodyHtml(string _responseBodyHtml) {
    this._responseBodyHtml = _responseBodyHtml;
    return this;
  }

  /**
   * Response body in plain text format. If both `response_body_plain_text` and `response_body_html`
   * are specified, `response_body_html` will be used.
   * @return value or {@code null} for none
   */
  public string getResponseBodyPlainText() {
    return _responseBodyPlainText;
  }
  /**
   * Response body in plain text format. If both `response_body_plain_text` and `response_body_html`
   * are specified, `response_body_html` will be used.
   * @param responseBodyPlainText responseBodyPlainText or {@code null} for none
   */
  public VacationSettings setResponseBodyPlainText(string _responseBodyPlainText) {
    this._responseBodyPlainText = _responseBodyPlainText;
    return this;
  }

  /**
   * Optional text to prepend to the subject line in vacation responses. In order to enable auto-
   * replies, either the response subject or the response body must be nonempty.
   * @return value or {@code null} for none
   */
  public string getResponseSubject() {
    return _responseSubject;
  }
  /**
   * Optional text to prepend to the subject line in vacation responses. In order to enable auto-
   * replies, either the response subject or the response body must be nonempty.
   * @param responseSubject responseSubject or {@code null} for none
   */
  public VacationSettings setResponseSubject(string _responseSubject) {
    this._responseSubject = _responseSubject;
    return this;
  }

  /**
   * Flag that determines whether responses are sent to recipients who are not in the user's list of
   * contacts.
   * @return value or {@code null} for none
   */
  public Nullable!bool getRestrictToContacts() {
    return _restrictToContacts;
  }
  /**
   * Flag that determines whether responses are sent to recipients who are not in the user's list of
   * contacts.
   * @param restrictToContacts restrictToContacts or {@code null} for none
   */
  public VacationSettings setRestrictToContacts(Nullable!bool _restrictToContacts) {
    this._restrictToContacts = _restrictToContacts;
    return this;
  }

  /**
   * Flag that determines whether responses are sent to recipients who are outside of the user's
   * domain. This feature is only available for G Suite users.
   * @return value or {@code null} for none
   */
  public Nullable!bool getRestrictToDomain() {
    return _restrictToDomain;
  }
  /**
   * Flag that determines whether responses are sent to recipients who are outside of the user's
   * domain. This feature is only available for G Suite users.
   * @param restrictToDomain restrictToDomain or {@code null} for none
   */
  public VacationSettings setRestrictToDomain(Nullable!bool _restrictToDomain) {
    this._restrictToDomain = _restrictToDomain;
    return this;
  }

  /**
   * An optional start time for sending auto-replies (epoch ms). When this is specified, Gmail will
   * automatically reply only to messages that it receives after the start time. If both `startTime`
   * and `endTime` are specified, `startTime` must precede `endTime`.
   * @return value or {@code null} for none
   */
  public MyNullable!long getStartTime() {
    return _startTime;
  }
  /**
   * An optional start time for sending auto-replies (epoch ms). When this is specified, Gmail will
   * automatically reply only to messages that it receives after the start time. If both `startTime`
   * and `endTime` are specified, `startTime` must precede `endTime`.
   * @param startTime startTime or {@code null} for none
   */
  public VacationSettings setStartTime(MyNullable!long _startTime) {
    this._startTime = _startTime;
    return this;
  }

}