/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

module Google.Apis.Gmail.v1.GmailScopes;

enum Scopes: int {
  MAIL_GOOGLE_COM,
  GMAIL_ADDONS_CURRENT_ACTION_COMPOSE,
  GMAIL_ADDONS_CURRENT_MESSAGE_ACTION,
  GMAIL_ADDONS_CURRENT_MESSAGE_METADATA,
  GMAIL_ADDONS_CURRENT_MESSAGE_READONLY,
  GMAIL_COMPOSE,
  GMAIL_INSERT,
  GMAIL_LABELS,
  GMAIL_METADATA,
  GMAIL_MODIFY,
  GMAIL_READONLY,
  GMAIL_SEND,
  GMAIL_SETTINGS_BASIC,
  GMAIL_SETTINGS_SHARING,
};

/**
 * Available OAuth 2.0 scopes for use with the Gmail API.
 *
 * @since 1.4
 */
public class GmailScopes {

  /**
   * Returns an unmodifiable set that contains all scopes declared by this class.
   *
   * @since 1.16
   */
  public static string[] all() {
    import std.traits: EnumMembers;
    
    auto noOfScopes = EnumMembers!Scopes.length;
    string[] _scopes = new string[noOfScopes];
    
    _scopes[Scopes.MAIL_GOOGLE_COM] = "https://mail.google.com/"; 
    _scopes[Scopes.GMAIL_ADDONS_CURRENT_ACTION_COMPOSE] = "https://www.googleapis.com/auth/gmail.addons.current.action.compose"; 
    _scopes[Scopes.GMAIL_ADDONS_CURRENT_MESSAGE_ACTION] = "https://www.googleapis.com/auth/gmail.addons.current.message.action"; 
    _scopes[Scopes.GMAIL_ADDONS_CURRENT_MESSAGE_METADATA] = "https://www.googleapis.com/auth/gmail.addons.current.message.metadata"; 
    _scopes[Scopes.GMAIL_ADDONS_CURRENT_MESSAGE_READONLY] = "https://www.googleapis.com/auth/gmail.addons.current.message.readonly"; 
    _scopes[Scopes.GMAIL_COMPOSE] = "https://www.googleapis.com/auth/gmail.compose"; 
    _scopes[Scopes.GMAIL_INSERT] = "https://www.googleapis.com/auth/gmail.insert"; 
    _scopes[Scopes.GMAIL_LABELS] = "https://www.googleapis.com/auth/gmail.labels"; 
    _scopes[Scopes.GMAIL_METADATA] = "https://www.googleapis.com/auth/gmail.metadata"; 
    _scopes[Scopes.GMAIL_MODIFY] = "https://www.googleapis.com/auth/gmail.modify"; 
    _scopes[Scopes.GMAIL_READONLY] = "https://www.googleapis.com/auth/gmail.readonly"; 
    _scopes[Scopes.GMAIL_SEND] = "https://www.googleapis.com/auth/gmail.send"; 
    _scopes[Scopes.GMAIL_SETTINGS_BASIC] = "https://www.googleapis.com/auth/gmail.settings.basic"; 
    _scopes[Scopes.GMAIL_SETTINGS_SHARING] = "https://www.googleapis.com/auth/gmail.settings.sharing"; 
    return _scopes;
  }

  private this() {}
}
